

create table historic_data (
    id serial primary key not null,
    exchange_name varchar(50),
    globaltradeid numeric,
    tradeid numeric,
    created_on varchar(100),
    quantity numeric,
    price numeric, 
    total numeric,
    fill_type varchar(20),
    order_type varchar(20)
);

create table chart_data (
    id serial primary key not null,
    exchange_name varchar(50),
    created_on varchar(100),
    high numeric,
    low numeric,
    opening numeric,
    closing numeric,
    volume numeric,
    quotevolume numeric,
    basevolume numeric,
    weightedaverage numeric
);

create table pos_data(
    id serial primary key not null,
    posid varchar(20),
    apienabled varchar(20),
    network varchar(20),
    network_url varchar(100),
    launched varchar(20),
    last_updated varchar(20),
    immature varchar(20),
    live varchar(20),
    voted numeric,
    missed numeric,
    poolfees numeric,
    proportionlive numeric,
    proportionmissed numeric,
    usercount numeric,
    usercountactive numeric,
    apiversionssupported varchar(20)[],
    created_on TIME
);

create table pow_data(
    id serial primary key not null,
    powid numeric,
    hashrate numeric,
    efficiency numeric,
    progress numeric,
    workers numeric,
    currentnetworkblock numeric,
    nextnetworkblock numeric,
    lastblock numeric,
    networkdiff numeric,
    esttime numeric,
    estshare numeric,
    timesincelast numeric,
    nethashrate numeric,
    blocksfound numeric,
    totalminers numeric,
    created_time numeric,
    networkdifficulty numeric,
    coinprice numeric,
    btcprice numeric,
    est numeric,
    created_on numeric,
    blocksper numeric,
    luck numeric,
    ppshare numeric,
    totalkickback numeric,
    success varchar(20),
    lastupdate numeric,
    name varchar(20),
    port numeric,
    fees numeric,
    estimatecurrent numeric,
    estimatelast24h numeric,
    actual124h numeric,
    mbtcmhfactor numeric,
    hashratelast24h numeric,
    rentalcurrent numeric,
    height numeric,
    blocks24h numeric,
    btc24h numeric,
    currentheight numeric,
    total numeric,
    pos numeric,
    pow numeric,
    dev numeric
);

