

create table historic_data (
    id serial primary key not null,
    exchange_name varchar(50),
    globaltradeid float,
    tradeid float,
    quantity float,
    price float, 
    total float,
    fill_type varchar(20),
    order_type varchar(20),
    created_on timestamp
);

create table chart_data (
    id serial primary key not null,
    exchange_name varchar(50),
    high float,
    low float,
    opening float,
    closing float,
    volume float,
    quotevolume float,
    basevolume float,
    weightedaverage float,
    created_on timestamp
);

create table pos_data(
    id serial primary key not null,
    posid varchar(20),
    apienabled boolean,
    network varchar(20),
    network_url varchar(100),
    launched bigint,
    last_updated bigint,
    immature integer,
    live integer,
    voted integer,
    missed integer,
    poolfees float,
    proportionlive float,
    proportionmissed float,
    usercount integer,
    usercountactive integer,
    apiversionssupported integer[],
    created_on date
);

create table pow_data(
    id serial primary key not null,
    powid float,
    hashrate float,
    efficiency float,
    progress float,
    workers float,
    currentnetworkblock float,
    nextnetworkblock float,
    lastblock float,
    networkdiff float,
    esttime timestamp,
    estshare float,
    timesincelast float,
    nethashrate float,
    blocksfound float,
    totalminers float,
    networkdifficulty float,
    coinprice varchar(30),
    btcprice varchar(30),
    est float,
    created_on float,
    blocksper float,
    luck float,
    ppshare float,
    totalkickback float,
    success varchar(20),
    lastupdate float,
    name varchar(20),
    port float,
    fees float,
    estimatecurrent float,
    estimatelast24h float,
    actual124h float,
    mbtcmhfactor float,
    hashratelast24h float,
    rentalcurrent float,
    height float,
    blocks24h float,
    btc24h float,
    currentheight float,
    total float,
    pos float,
    pow float,
    dev float,
    created_time date
);

