// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Block           string
	Exchange        string
	ExchangeTick    string
	Github          string
	Heartbeat       string
	Mempool         string
	MempoolBin      string
	NetworkSnapshot string
	Node            string
	PowData         string
	Reddit          string
	Twitter         string
	Vote            string
	VSP             string
	VSPTick         string
	Youtube         string
}{
	Block:           "block",
	Exchange:        "exchange",
	ExchangeTick:    "exchange_tick",
	Github:          "github",
	Heartbeat:       "heartbeat",
	Mempool:         "mempool",
	MempoolBin:      "mempool_bin",
	NetworkSnapshot: "network_snapshot",
	Node:            "node",
	PowData:         "pow_data",
	Reddit:          "reddit",
	Twitter:         "twitter",
	Vote:            "vote",
	VSP:             "vsp",
	VSPTick:         "vsp_tick",
	Youtube:         "youtube",
}
