// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Block              string
	CommunityStat      string
	Exchange           string
	ExchangeTick       string
	Github             string
	Heartbeat          string
	Mempool            string
	MempoolBin         string
	NetworkSnapshot    string
	NetworkSnapshotBin string
	Node               string
	PowBin             string
	PowData            string
	Propagation        string
	Reddit             string
	Twitter            string
	Vote               string
	VSP                string
	VSPTick            string
	VSPTickBin         string
	Youtube            string
}{
	Block:              "block",
	CommunityStat:      "community_stat",
	Exchange:           "exchange",
	ExchangeTick:       "exchange_tick",
	Github:             "github",
	Heartbeat:          "heartbeat",
	Mempool:            "mempool",
	MempoolBin:         "mempool_bin",
	NetworkSnapshot:    "network_snapshot",
	NetworkSnapshotBin: "network_snapshot_bin",
	Node:               "node",
	PowBin:             "pow_bin",
	PowData:            "pow_data",
	Propagation:        "propagation",
	Reddit:             "reddit",
	Twitter:            "twitter",
	Vote:               "vote",
	VSP:                "vsp",
	VSPTick:            "vsp_tick",
	VSPTickBin:         "vsp_tick_bin",
	Youtube:            "youtube",
}
