// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCommunityStats(t *testing.T) {
	t.Parallel()

	query := CommunityStats()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCommunityStatsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommunityStatsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CommunityStats().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommunityStatsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CommunityStatSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommunityStatsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CommunityStatExists(ctx, tx, o.Date, o.Platform, o.Account, o.Metric)
	if err != nil {
		t.Errorf("Unable to check if CommunityStat exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CommunityStatExists to return true, but got false.")
	}
}

func testCommunityStatsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	communityStatFound, err := FindCommunityStat(ctx, tx, o.Date, o.Platform, o.Account, o.Metric)
	if err != nil {
		t.Error(err)
	}

	if communityStatFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCommunityStatsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CommunityStats().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCommunityStatsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CommunityStats().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCommunityStatsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	communityStatOne := &CommunityStat{}
	communityStatTwo := &CommunityStat{}
	if err = randomize.Struct(seed, communityStatOne, communityStatDBTypes, false, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}
	if err = randomize.Struct(seed, communityStatTwo, communityStatDBTypes, false, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = communityStatOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = communityStatTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CommunityStats().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCommunityStatsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	communityStatOne := &CommunityStat{}
	communityStatTwo := &CommunityStat{}
	if err = randomize.Struct(seed, communityStatOne, communityStatDBTypes, false, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}
	if err = randomize.Struct(seed, communityStatTwo, communityStatDBTypes, false, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = communityStatOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = communityStatTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testCommunityStatsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCommunityStatsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(communityStatColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCommunityStatsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCommunityStatsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CommunityStatSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCommunityStatsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CommunityStats().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	communityStatDBTypes = map[string]string{`Date`: `bigint`, `Platform`: `character varying`, `Account`: `character varying`, `Metric`: `character varying`, `Value`: `bigint`}
	_                    = bytes.MinRead
)

func testCommunityStatsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(communityStatPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(communityStatAllColumns) == len(communityStatPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCommunityStatsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(communityStatAllColumns) == len(communityStatPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CommunityStat{}
	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, communityStatDBTypes, true, communityStatPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(communityStatAllColumns, communityStatPrimaryKeyColumns) {
		fields = communityStatAllColumns
	} else {
		fields = strmangle.SetComplement(
			communityStatAllColumns,
			communityStatPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CommunityStatSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCommunityStatsUpsert(t *testing.T) {
	t.Parallel()

	if len(communityStatAllColumns) == len(communityStatPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CommunityStat{}
	if err = randomize.Struct(seed, &o, communityStatDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CommunityStat: %s", err)
	}

	count, err := CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, communityStatDBTypes, false, communityStatPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommunityStat struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CommunityStat: %s", err)
	}

	count, err = CommunityStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
