// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"github.com/volatiletech/sqlboiler/types"
)

// ChartDatum is an object representing the database table.
type ChartDatum struct {
	ID              int               `boil:"id" json:"id" toml:"id" yaml:"id"`
	ExchangeName    null.String       `boil:"exchange_name" json:"exchange_name,omitempty" toml:"exchange_name" yaml:"exchange_name,omitempty"`
	CreatedOn       null.String       `boil:"created_on" json:"created_on,omitempty" toml:"created_on" yaml:"created_on,omitempty"`
	High            types.NullDecimal `boil:"high" json:"high,omitempty" toml:"high" yaml:"high,omitempty"`
	Low             types.NullDecimal `boil:"low" json:"low,omitempty" toml:"low" yaml:"low,omitempty"`
	Opening         types.NullDecimal `boil:"opening" json:"opening,omitempty" toml:"opening" yaml:"opening,omitempty"`
	Closing         types.NullDecimal `boil:"closing" json:"closing,omitempty" toml:"closing" yaml:"closing,omitempty"`
	Volume          types.NullDecimal `boil:"volume" json:"volume,omitempty" toml:"volume" yaml:"volume,omitempty"`
	Quotevolume     types.NullDecimal `boil:"quotevolume" json:"quotevolume,omitempty" toml:"quotevolume" yaml:"quotevolume,omitempty"`
	Basevolume      types.NullDecimal `boil:"basevolume" json:"basevolume,omitempty" toml:"basevolume" yaml:"basevolume,omitempty"`
	Weightedaverage types.NullDecimal `boil:"weightedaverage" json:"weightedaverage,omitempty" toml:"weightedaverage" yaml:"weightedaverage,omitempty"`

	R *chartDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L chartDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChartDatumColumns = struct {
	ID              string
	ExchangeName    string
	CreatedOn       string
	High            string
	Low             string
	Opening         string
	Closing         string
	Volume          string
	Quotevolume     string
	Basevolume      string
	Weightedaverage string
}{
	ID:              "id",
	ExchangeName:    "exchange_name",
	CreatedOn:       "created_on",
	High:            "high",
	Low:             "low",
	Opening:         "opening",
	Closing:         "closing",
	Volume:          "volume",
	Quotevolume:     "quotevolume",
	Basevolume:      "basevolume",
	Weightedaverage: "weightedaverage",
}

// ChartDatumRels is where relationship names are stored.
var ChartDatumRels = struct {
}{}

// chartDatumR is where relationships are stored.
type chartDatumR struct {
}

// NewStruct creates a new relationship struct
func (*chartDatumR) NewStruct() *chartDatumR {
	return &chartDatumR{}
}

// chartDatumL is where Load methods for each relationship are stored.
type chartDatumL struct{}

var (
	chartDatumColumns               = []string{"id", "exchange_name", "created_on", "high", "low", "opening", "closing", "volume", "quotevolume", "basevolume", "weightedaverage"}
	chartDatumColumnsWithoutDefault = []string{"exchange_name", "created_on", "high", "low", "opening", "closing", "volume", "quotevolume", "basevolume", "weightedaverage"}
	chartDatumColumnsWithDefault    = []string{"id"}
	chartDatumPrimaryKeyColumns     = []string{"id"}
)

type (
	// ChartDatumSlice is an alias for a slice of pointers to ChartDatum.
	// This should generally be used opposed to []ChartDatum.
	ChartDatumSlice []*ChartDatum
	// ChartDatumHook is the signature for custom ChartDatum hook methods
	ChartDatumHook func(context.Context, boil.ContextExecutor, *ChartDatum) error

	chartDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	chartDatumType                 = reflect.TypeOf(&ChartDatum{})
	chartDatumMapping              = queries.MakeStructMapping(chartDatumType)
	chartDatumPrimaryKeyMapping, _ = queries.BindMapping(chartDatumType, chartDatumMapping, chartDatumPrimaryKeyColumns)
	chartDatumInsertCacheMut       sync.RWMutex
	chartDatumInsertCache          = make(map[string]insertCache)
	chartDatumUpdateCacheMut       sync.RWMutex
	chartDatumUpdateCache          = make(map[string]updateCache)
	chartDatumUpsertCacheMut       sync.RWMutex
	chartDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var chartDatumBeforeInsertHooks []ChartDatumHook
var chartDatumBeforeUpdateHooks []ChartDatumHook
var chartDatumBeforeDeleteHooks []ChartDatumHook
var chartDatumBeforeUpsertHooks []ChartDatumHook

var chartDatumAfterInsertHooks []ChartDatumHook
var chartDatumAfterSelectHooks []ChartDatumHook
var chartDatumAfterUpdateHooks []ChartDatumHook
var chartDatumAfterDeleteHooks []ChartDatumHook
var chartDatumAfterUpsertHooks []ChartDatumHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ChartDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ChartDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ChartDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ChartDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ChartDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ChartDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ChartDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ChartDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ChartDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range chartDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddChartDatumHook registers your hook function for all future operations.
func AddChartDatumHook(hookPoint boil.HookPoint, chartDatumHook ChartDatumHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		chartDatumBeforeInsertHooks = append(chartDatumBeforeInsertHooks, chartDatumHook)
	case boil.BeforeUpdateHook:
		chartDatumBeforeUpdateHooks = append(chartDatumBeforeUpdateHooks, chartDatumHook)
	case boil.BeforeDeleteHook:
		chartDatumBeforeDeleteHooks = append(chartDatumBeforeDeleteHooks, chartDatumHook)
	case boil.BeforeUpsertHook:
		chartDatumBeforeUpsertHooks = append(chartDatumBeforeUpsertHooks, chartDatumHook)
	case boil.AfterInsertHook:
		chartDatumAfterInsertHooks = append(chartDatumAfterInsertHooks, chartDatumHook)
	case boil.AfterSelectHook:
		chartDatumAfterSelectHooks = append(chartDatumAfterSelectHooks, chartDatumHook)
	case boil.AfterUpdateHook:
		chartDatumAfterUpdateHooks = append(chartDatumAfterUpdateHooks, chartDatumHook)
	case boil.AfterDeleteHook:
		chartDatumAfterDeleteHooks = append(chartDatumAfterDeleteHooks, chartDatumHook)
	case boil.AfterUpsertHook:
		chartDatumAfterUpsertHooks = append(chartDatumAfterUpsertHooks, chartDatumHook)
	}
}

// One returns a single chartDatum record from the query.
func (q chartDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ChartDatum, error) {
	o := &ChartDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for chart_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ChartDatum records from the query.
func (q chartDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChartDatumSlice, error) {
	var o []*ChartDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ChartDatum slice")
	}

	if len(chartDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ChartDatum records in the query.
func (q chartDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count chart_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q chartDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if chart_data exists")
	}

	return count > 0, nil
}

// ChartData retrieves all the records using an executor.
func ChartData(mods ...qm.QueryMod) chartDatumQuery {
	mods = append(mods, qm.From("\"chart_data\""))
	return chartDatumQuery{NewQuery(mods...)}
}

// FindChartDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChartDatum(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*ChartDatum, error) {
	chartDatumObj := &ChartDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"chart_data\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, chartDatumObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from chart_data")
	}

	return chartDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChartDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no chart_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chartDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	chartDatumInsertCacheMut.RLock()
	cache, cached := chartDatumInsertCache[key]
	chartDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			chartDatumColumns,
			chartDatumColumnsWithDefault,
			chartDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(chartDatumType, chartDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(chartDatumType, chartDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"chart_data\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"chart_data\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into chart_data")
	}

	if !cached {
		chartDatumInsertCacheMut.Lock()
		chartDatumInsertCache[key] = cache
		chartDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ChartDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChartDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	chartDatumUpdateCacheMut.RLock()
	cache, cached := chartDatumUpdateCache[key]
	chartDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			chartDatumColumns,
			chartDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update chart_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"chart_data\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, chartDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(chartDatumType, chartDatumMapping, append(wl, chartDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update chart_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for chart_data")
	}

	if !cached {
		chartDatumUpdateCacheMut.Lock()
		chartDatumUpdateCache[key] = cache
		chartDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q chartDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for chart_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for chart_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChartDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chartDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"chart_data\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, chartDatumPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in chartDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all chartDatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChartDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no chart_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chartDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	chartDatumUpsertCacheMut.RLock()
	cache, cached := chartDatumUpsertCache[key]
	chartDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			chartDatumColumns,
			chartDatumColumnsWithDefault,
			chartDatumColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			chartDatumColumns,
			chartDatumPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert chart_data, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(chartDatumPrimaryKeyColumns))
			copy(conflict, chartDatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"chart_data\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(chartDatumType, chartDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(chartDatumType, chartDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert chart_data")
	}

	if !cached {
		chartDatumUpsertCacheMut.Lock()
		chartDatumUpsertCache[key] = cache
		chartDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ChartDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChartDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ChartDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), chartDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"chart_data\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from chart_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for chart_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q chartDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no chartDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from chart_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for chart_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChartDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ChartDatum slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(chartDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chartDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"chart_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chartDatumPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from chartDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for chart_data")
	}

	if len(chartDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChartDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChartDatum(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChartDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChartDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chartDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"chart_data\".* FROM \"chart_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chartDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ChartDatumSlice")
	}

	*o = slice

	return nil
}

// ChartDatumExists checks if the ChartDatum row exists.
func ChartDatumExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"chart_data\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if chart_data exists")
	}

	return exists, nil
}
