// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// HistoricDatum is an object representing the database table.
type HistoricDatum struct {
	ID            int          `boil:"id" json:"id" toml:"id" yaml:"id"`
	ExchangeName  null.String  `boil:"exchange_name" json:"exchange_name,omitempty" toml:"exchange_name" yaml:"exchange_name,omitempty"`
	Globaltradeid null.Float64 `boil:"globaltradeid" json:"globaltradeid,omitempty" toml:"globaltradeid" yaml:"globaltradeid,omitempty"`
	Tradeid       null.Float64 `boil:"tradeid" json:"tradeid,omitempty" toml:"tradeid" yaml:"tradeid,omitempty"`
	Quantity      null.Float64 `boil:"quantity" json:"quantity,omitempty" toml:"quantity" yaml:"quantity,omitempty"`
	Price         null.Float64 `boil:"price" json:"price,omitempty" toml:"price" yaml:"price,omitempty"`
	Total         null.Float64 `boil:"total" json:"total,omitempty" toml:"total" yaml:"total,omitempty"`
	FillType      null.String  `boil:"fill_type" json:"fill_type,omitempty" toml:"fill_type" yaml:"fill_type,omitempty"`
	OrderType     null.String  `boil:"order_type" json:"order_type,omitempty" toml:"order_type" yaml:"order_type,omitempty"`
	CreatedOn     null.Time    `boil:"created_on" json:"created_on,omitempty" toml:"created_on" yaml:"created_on,omitempty"`

	R *historicDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L historicDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HistoricDatumColumns = struct {
	ID            string
	ExchangeName  string
	Globaltradeid string
	Tradeid       string
	Quantity      string
	Price         string
	Total         string
	FillType      string
	OrderType     string
	CreatedOn     string
}{
	ID:            "id",
	ExchangeName:  "exchange_name",
	Globaltradeid: "globaltradeid",
	Tradeid:       "tradeid",
	Quantity:      "quantity",
	Price:         "price",
	Total:         "total",
	FillType:      "fill_type",
	OrderType:     "order_type",
	CreatedOn:     "created_on",
}

// HistoricDatumRels is where relationship names are stored.
var HistoricDatumRels = struct {
}{}

// historicDatumR is where relationships are stored.
type historicDatumR struct {
}

// NewStruct creates a new relationship struct
func (*historicDatumR) NewStruct() *historicDatumR {
	return &historicDatumR{}
}

// historicDatumL is where Load methods for each relationship are stored.
type historicDatumL struct{}

var (
	historicDatumColumns               = []string{"id", "exchange_name", "globaltradeid", "tradeid", "quantity", "price", "total", "fill_type", "order_type", "created_on"}
	historicDatumColumnsWithoutDefault = []string{"exchange_name", "globaltradeid", "tradeid", "quantity", "price", "total", "fill_type", "order_type", "created_on"}
	historicDatumColumnsWithDefault    = []string{"id"}
	historicDatumPrimaryKeyColumns     = []string{"id"}
)

type (
	// HistoricDatumSlice is an alias for a slice of pointers to HistoricDatum.
	// This should generally be used opposed to []HistoricDatum.
	HistoricDatumSlice []*HistoricDatum
	// HistoricDatumHook is the signature for custom HistoricDatum hook methods
	HistoricDatumHook func(context.Context, boil.ContextExecutor, *HistoricDatum) error

	historicDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	historicDatumType                 = reflect.TypeOf(&HistoricDatum{})
	historicDatumMapping              = queries.MakeStructMapping(historicDatumType)
	historicDatumPrimaryKeyMapping, _ = queries.BindMapping(historicDatumType, historicDatumMapping, historicDatumPrimaryKeyColumns)
	historicDatumInsertCacheMut       sync.RWMutex
	historicDatumInsertCache          = make(map[string]insertCache)
	historicDatumUpdateCacheMut       sync.RWMutex
	historicDatumUpdateCache          = make(map[string]updateCache)
	historicDatumUpsertCacheMut       sync.RWMutex
	historicDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var historicDatumBeforeInsertHooks []HistoricDatumHook
var historicDatumBeforeUpdateHooks []HistoricDatumHook
var historicDatumBeforeDeleteHooks []HistoricDatumHook
var historicDatumBeforeUpsertHooks []HistoricDatumHook

var historicDatumAfterInsertHooks []HistoricDatumHook
var historicDatumAfterSelectHooks []HistoricDatumHook
var historicDatumAfterUpdateHooks []HistoricDatumHook
var historicDatumAfterDeleteHooks []HistoricDatumHook
var historicDatumAfterUpsertHooks []HistoricDatumHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HistoricDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HistoricDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HistoricDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HistoricDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HistoricDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HistoricDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HistoricDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HistoricDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HistoricDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range historicDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHistoricDatumHook registers your hook function for all future operations.
func AddHistoricDatumHook(hookPoint boil.HookPoint, historicDatumHook HistoricDatumHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		historicDatumBeforeInsertHooks = append(historicDatumBeforeInsertHooks, historicDatumHook)
	case boil.BeforeUpdateHook:
		historicDatumBeforeUpdateHooks = append(historicDatumBeforeUpdateHooks, historicDatumHook)
	case boil.BeforeDeleteHook:
		historicDatumBeforeDeleteHooks = append(historicDatumBeforeDeleteHooks, historicDatumHook)
	case boil.BeforeUpsertHook:
		historicDatumBeforeUpsertHooks = append(historicDatumBeforeUpsertHooks, historicDatumHook)
	case boil.AfterInsertHook:
		historicDatumAfterInsertHooks = append(historicDatumAfterInsertHooks, historicDatumHook)
	case boil.AfterSelectHook:
		historicDatumAfterSelectHooks = append(historicDatumAfterSelectHooks, historicDatumHook)
	case boil.AfterUpdateHook:
		historicDatumAfterUpdateHooks = append(historicDatumAfterUpdateHooks, historicDatumHook)
	case boil.AfterDeleteHook:
		historicDatumAfterDeleteHooks = append(historicDatumAfterDeleteHooks, historicDatumHook)
	case boil.AfterUpsertHook:
		historicDatumAfterUpsertHooks = append(historicDatumAfterUpsertHooks, historicDatumHook)
	}
}

// One returns a single historicDatum record from the query.
func (q historicDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*HistoricDatum, error) {
	o := &HistoricDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for historic_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all HistoricDatum records from the query.
func (q historicDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (HistoricDatumSlice, error) {
	var o []*HistoricDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to HistoricDatum slice")
	}

	if len(historicDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all HistoricDatum records in the query.
func (q historicDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count historic_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q historicDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if historic_data exists")
	}

	return count > 0, nil
}

// HistoricData retrieves all the records using an executor.
func HistoricData(mods ...qm.QueryMod) historicDatumQuery {
	mods = append(mods, qm.From("\"historic_data\""))
	return historicDatumQuery{NewQuery(mods...)}
}

// FindHistoricDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHistoricDatum(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*HistoricDatum, error) {
	historicDatumObj := &HistoricDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"historic_data\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, historicDatumObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from historic_data")
	}

	return historicDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *HistoricDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no historic_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(historicDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	historicDatumInsertCacheMut.RLock()
	cache, cached := historicDatumInsertCache[key]
	historicDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			historicDatumColumns,
			historicDatumColumnsWithDefault,
			historicDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"historic_data\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"historic_data\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into historic_data")
	}

	if !cached {
		historicDatumInsertCacheMut.Lock()
		historicDatumInsertCache[key] = cache
		historicDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the HistoricDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *HistoricDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	historicDatumUpdateCacheMut.RLock()
	cache, cached := historicDatumUpdateCache[key]
	historicDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			historicDatumColumns,
			historicDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update historic_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"historic_data\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, historicDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, append(wl, historicDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update historic_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for historic_data")
	}

	if !cached {
		historicDatumUpdateCacheMut.Lock()
		historicDatumUpdateCache[key] = cache
		historicDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q historicDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for historic_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for historic_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HistoricDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historicDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"historic_data\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, historicDatumPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in historicDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all historicDatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *HistoricDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no historic_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(historicDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	historicDatumUpsertCacheMut.RLock()
	cache, cached := historicDatumUpsertCache[key]
	historicDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			historicDatumColumns,
			historicDatumColumnsWithDefault,
			historicDatumColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			historicDatumColumns,
			historicDatumPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert historic_data, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(historicDatumPrimaryKeyColumns))
			copy(conflict, historicDatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"historic_data\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert historic_data")
	}

	if !cached {
		historicDatumUpsertCacheMut.Lock()
		historicDatumUpsertCache[key] = cache
		historicDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single HistoricDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HistoricDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no HistoricDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), historicDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"historic_data\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from historic_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for historic_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q historicDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no historicDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from historic_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for historic_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HistoricDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no HistoricDatum slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(historicDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historicDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"historic_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, historicDatumPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from historicDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for historic_data")
	}

	if len(historicDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HistoricDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindHistoricDatum(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HistoricDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HistoricDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historicDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"historic_data\".* FROM \"historic_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, historicDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in HistoricDatumSlice")
	}

	*o = slice

	return nil
}

// HistoricDatumExists checks if the HistoricDatum row exists.
func HistoricDatumExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"historic_data\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if historic_data exists")
	}

	return exists, nil
}
