// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ChartData", testChartDataUpsert)

	t.Run("HistoricData", testHistoricDataUpsert)

	t.Run("PosData", testPosDataUpsert)

	t.Run("PowData", testPowDataUpsert)
}
